name: Docker Image CI

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>  # Replace with your AWS region
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'  # Use the latest version of kubectl
        
    - name: Deploy to AWS EKS
      run: kubectl apply -f path/to/your/kubernetes/manifests
